id: P7BCB848C
initial_creation_type: input
source_metadata:
  title: Vajravidāraṇa Series
  language: bo
  description: 'A series of texts related to the deity Vajravidāraṇa (rdo rje rnam
    ‘joms), a wrathful form of Vajrapāṇi:'
  volume:
    5fa4e7dcd2db469ebf47682e8cdf0425:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Dhāraṇī
created_at: '2022-03-01T06:33:31.555576'
last_modified_at: '2022-03-01T06:33:31.555580'
statistics:
  total_words: 1397
  total_non_words: 388
quality:
  non_words_ratio: 0.28
